"""add posts and ingest_cursor

Revision ID: 7f960ab77012
Revises: 4d30889a9e40
Create Date: 2026-09-21 17:13:52.595388
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '7f960ab77012'
down_revision = '4d30889a9e40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingest_cursor',
    sa.Column('stream', sa.String(), nullable=False),
    sa.Column('cursor', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('stream')
    )
    op.create_table('posts',
    sa.Column('uri', sa.String(), nullable=False),
    sa.Column('cid', sa.String(), nullable=False),
    sa.Column('author_did', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('langs', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column(
        'first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False
    ),
    sa.PrimaryKeyConstraint('uri')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_table('ingest_cursor')
    # ### end Alembic commands ###
